sudo: required
language: node_js
node_js:
- 4.2.2
env:
  global:
  - ENCRYPTION_LABEL: 3bf8f2b432cb
  - COMMIT_AUTHOR: Igor Mykhaylyuk
  - COMMIT_AUTHOR_EMAIL: igor13luk@gmail.com
matrix:
  fast_finish: true
before_install:
- npm install -g npm
install:
- npm install
before_script: 
- export NODE_ENV=production
script:
- npm test
- npm run build
after_success:
- bash ./deploy.sh
git:
  depth: 50
branches:
  only:
  - development
